name: InstanceMechanics
main: me.vaqxine.InstanceMechanics.InstanceMechanics
version: 1.0
commands:
  instance:
    description: Root command.
    usage: /<command>
  isay:
    description: Instance tell message.
    usage: /<command>
  debuffcrystal:
    description: Spawn debuff crystal at coordinates.
    usage: /<command>
  drlightning:
    description: Spawns a lightning bolt.
    usage: /<command>
  drreplacenear:
    description: Replaces nearby blocks.
    usage: /<command>
  bosstp:
    description: Teleport to boss room if mobs are dead.
    usage: /<command>