name: TutorialMechanics
main: me.vaqxine.TutorialMechanics.TutorialMechanics
version: 1.0
commands:
  tutorial:
    description: Root command.
    usage: /<command>
  skip:
    description: Skips the tutorial island.
    usage: /<command>