name: HiveServer
main: me.vaqxine.HiveServer.HiveServer
version: 1.0
loadbefore: [HiveClient, RealmMechanics]
commands:
  classicrollout:
    description: Classic rollout
    usage: /<command>
  rollout:
    description: Rollout world and plugins.
    usage: /<command>
  rolloutall:
    description: Rollout world and plugins to all servers.
    usage: /<command>
  cycleall:
    description: Reboot all servers.
    usage: /<command>
  cycle:
    description: Reboot a specific server.
    usage: /<command>