name: Hive
main: me.vaqxine.Hive.Hive
version: 1.0
softdepend: [RemoteEntities]
commands:
  hquery:
    description: Query debug command.
    usage: /<command>
  benchmark:
    description: Run a benchmark.
    usage: /<command>
  drsave:
    description: Save DR stuff.
    usage: /<command>
  drload:
    description: Load DR stuff.
    usage: /<command>
  whois:
    description: Get a bunch of data about currently logged in player.
    usage: /<command>
  logout:
    description: Logs out safely.
    usage: /<command>
    aliases: [camp, quit, safe]
  sync:
    description: Resyncs character.
    usage: /<command>
    aliases: [fix, desync]
  bio:
    description: Write character biography.
    usage: /<command>
    aliases: [biography, setbio, pbio]
  wipe:
    description: Wipes characters.
    usage: /<command>
  suicide:
    description: Kills player.
    usage: /<command>
    aliases: [killself]
  profile:
    description: Spits out link to player profile on website.
    usage: /<command>
    aliases: [profilelink]
  reboot:
    description: Next scheduled reboot time.
    usage: /<command>
    aliases: [restart, nextreboot]
  shard:
    description: Opens shard selection menu.
    usage: /<command>
    aliases: [servers, server, serverlist]