name: RealmMechanics
main: me.vaqxine.RealmMechanics.RealmMechanics
version: 1.0
commands:
  realm:
    description: Sets TITLE of realm.
    usage: /<command>
    aliases: [title]
  resetrealm:
    description: Resets your player owned realm.
    usage: /<command>
  setrealmtier:
    description: Set realm tier of a player.
    usage: /<command>