name: CommunityMechanics
main: me.vaqxine.CommunityMechanics.CommunityMechanics
version: 1.0
commands:
  add:
    description: Adds PLAYER to buddy list.
    usage: /<command>
    aliases: [addbuddy, addfriend, friend]
  delete:
    description: Delete PLAYER from ALL lists.
    usage: /<command>
    aliases: [del, delbuddy, remove]
  ignore:
    description: Adds PLAYER to ignore list.
    usage: /<command>
  crypt:
    description: Encrypt/Decrypt String information.
    usage: /<command>
  toggles:
    description: Opens toggle menu.
    usage: /<command>
    aliases: [togglemenu, viewtoggles, toggle]
  toggletells:
    description: Toggles recieving PMs.
    usage: /<command>
    aliases: [toggletell]
  toggleparty:
    description: Toggles recieving party invites.
    usage: /<command>
  toggleff:
    description: Toggles PvP against buddies.
    usage: /<command>
    aliases: [togglepvp, ff]
  debug:
    description: Toggles displaying debug messages.
    usage: /<command>
    aliases: [info, toggledebug]
  toggleglobal:
    description: Toggles displaying global chat.
    usage: /<command>
    aliases: [tgl]
  toggletradechat:
    description: Toggles displaying trade chat.
    usage: /<command>
    aliases: [ttc, toggletc, toggletchat]
  togglefilter:
    description: Toggles adult language filter.
    usage: /<command>
    aliases: [tfilter, filter]
  toggleguild:
    description: Toggles recieving guild invites.
    usage: /<command>
    aliases: [tguild, toggleguildinvites]
  togglepvp:
    description: Toggles any hits that result in you turning chaotic.
    usage: /<command>
    aliases: [tpvp]
  togglechaos:
    description: Toggles any hits that result in you turning chaotic.
    usage: /<command>
    aliases: [togglechaotic]
  toggletips:
    description: Toggles recieving tips.
    usage: /<command>
    aliases: [toggletip, disabletips, stoptips, enabletips]
  toggleprofile:
    description: Toggles displaying inventory and stats on website statistics.
    usage: /<command>
    aliases: [togglestats]
  togglestarterpack:
    description: Toggles getting starter items.
    usage: /<command>
  tips:
    description: Get a random tip.
    usage: /<command>
    aliases: [tip, protip]
  roll:
    description: Generates a random number.
    usage: /<command>
    aliases: [random, dice, ran]