name: LootMechanics
main: me.vaqxine.LootMechanics.LootMechanics
version: 1.0
commands:
  loot:
    description: Root plugin command.
    usage: /<command>
  showloot:
    description: Show loot.
    usage: /<command>
  hideloot:
    description: Hide loot.
    usage: /<command>
  loadloot:
    description: Loads new loot template files.
    usage: /<command>