name: GuildMechanics
main: me.vaqxine.GuildMechanics.GuildMechanics
version: 1.0
commands:
  guild:
    description: Root command.
    usage: /<command>
  ginvite:
    description: Invite player to guild.
    usage: /<command>
  gkick:
    description: Kick player from guild.
    usage: /<command>
  gquit:
    description: Quit guild.
    usage: /<command>
  gpromote:
    description: Promote to officer.
    usage: /<command>
  gdemote:
    description: Demote officer back to member.
    usage: /<command>
  gaccept:
    description: Accept guild invite.
    usage: /<command>
  gdecline:
    description: Decline guild invite.
    usage: /<command>
  g:
    description: Speak in guild chat.
    usage: /<command>
    aliases: [gchat]
  gmotd:
    description: Guild message of the day.
    usage: /<command>
    aliases: [motd]
  gbio:
    description: Sets and displays the guild biography.
    usage: /<command>
    aliases: [gbiography, guildbio, guildbiography, setguildbio, setguildbiography]
  gbanner:
    description: Uploads guild banner to website for highscores.
    usage: /<command>
    aliases: [guildbanner, setguildbanner, uploadbanner, uploadguildbanner, uploadgbanner]