name: ProfessionMechanics
main: me.vaqxine.ProfessionMechanics.ProfessionMechanics
version: 1.0
commands:
  prof:
    description: Root CMD.
    usage: /<command>
  setore:
    description: Ore placement command.
    usage: /<command>
  setfish:
    description: Fishing spot placement command.
    usage: /<command>
  showfish:
    description: Show fishing spots in area.
    usage: /<command>
  hidefish:
    description: Hide fishing spots in area.
    usage: /<command>