name: EcashMechanics
main: me.vaqxine.EcashMechanics.EcashMechanics
version: 1.0
commands:
  ecash:
    description: Open ecash shop.
    usage: /<command>
  checkecash:
    description: Check a player ecash level.
    usage: /<command>
  firewand:
    description: Adds firewand.
    usage: /<command>