name: RestrictionMechanics
main: me.vaqxine.RestrictionMechanics.RestrictionMechanics
version: 1.0
depend: [ItemMechanics]
commands:
  restrict:
    description: Root command.
    usage: /<command>
  zone:
    description: Refresh zone of player.
    usage: /<command>
  list:
    description: List all online players.
    usage: /<command> [group]
    aliases: [elist,online,eonline,playerlist,eplayerlist,plist,eplist,who,ewho]