name: ModerationMechanics
main: me.vaqxine.ModerationMechanics.ModerationMechanics
version: 1.0
commands:
  mute:
    description: Mutes player.
    usage: /<command>
  unmute:
    description: Unmutes player.
    usage: /<command>
  kick:
    description: Kicks player.
    usage: /<command>
  ipban:
    description: IP Ban.
    usage: /<command>
  ban:
    description: Bans player.
    usage: /<command>
  unban:
    description: Unbans player.
    usage: /<command>
  report:
    description: Report a player.
    usage: /<command>
  check:
    description: Check active reports.
    usage: /<command>
  stuck:
    description: Unstucks your character.
    usage: /<command>
    aliases: [unstuck]
  sayall:
    description: Sends a command to all players on server.
    usage: /<command> 
  lock:
    description: Lock login to all servers.
    usage: /<command> 
  unlock:
    description: Unlock login to all servers.
    usage: /<command> 
  banksee:
    description: Views player's bank.
    usage: /<command> 
  drtppos:
    description: Teleport to position.
    usage: /<command> 
  armorsee:
    description: Views player's armor.
    usage: /<command> 
  realmclone:
    description: Copy a player's realm.
    usage: /<command>
  playerclone:
    description: Copy a player's data.
    usage: /<command>
  drvanish:
    description: A better vanish.
    usage: /<command>
    aliases: [vanish, unvanish]