name: PermissionMechanics
main: me.vaqxine.PermissionMechanics.PermissionMechanics
version: 1.0
commands:
  setrank:
    description: Sets a users rank.
    usage: /<command>
  pmhelp:
    description: Player mod help.
    usage: /<command>
  gmhelp:
    description: Game mod help.
    usage: /<command>