name: DonationMechanics
main: me.vaqxine.DonationMechanics.DonationMechanics
version: 1.0
commands:
  tickdays:
    description: Ticks days of sdays_left forward 1 day.
    usage: /<command>
  givebeta:
    description: Give beta to the user.
    usage: /<command>
  givesub:
    description: Give sub to the user.
    usage: /<command>
  givesubplus:
    description: Give sub+ to the user.
    usage: /<command>
  addec:
    description: Add specified amount of ECASH to player.
    usage: /<command>
  removesubplus:
    description: Removes any sub/sub+ status.
    usage: /<command>
  removesub:
    description: Removes any sub/sub+ status.
    usage: /<command>
  accept:
    description: Accept given user into beta (nonpaying)
    usage: /<command>
  acceptall:
    description: Accept all users in accept.txt
    usage: /<command>
  addpet:
    description: Console command to add pet to player.
    usage: /<command>
  givesublife:
    description: Console command to give lifetime sub to a player.
    usage: /<command>
  rewardsublife:
    description: Gives 999 to all sub++
    usage: /<command>